export const currencies = [
    { country: "United States", code: "USD", symbol: "$" },
    { country: "Canada", code: "CAD", symbol: "CA$" },
    { country: "United Kingdom", code: "GBP", symbol: "£" },
    { country: "European Union", code: "EUR", symbol: "€" },
    { country: "Japan", code: "JPY", symbol: "¥" },
    { country: "Australia", code: "AUD", symbol: "A$" },
    { country: "New Zealand", code: "NZD", symbol: "NZ$" },
    { country: "Switzerland", code: "CHF", symbol: "CHF" },
    { country: "China", code: "CNY", symbol: "¥" },
    { country: "India", code: "INR", symbol: "₹" },
    { country: "Mexico", code: "MXN", symbol: "$" },
    { country: "Brazil", code: "BRL", symbol: "R$" },
    { country: "Russia", code: "RUB", symbol: "₽" },
    { country: "South Africa", code: "ZAR", symbol: "R" },
    { country: "Nigeria", code: "NGN", symbol: "₦" },
    { country: "Kenya", code: "KES", symbol: "KSh" },
    { country: "Ghana", code: "GHS", symbol: "₵" },
    { country: "Jamaica", code: "JMD", symbol: "J$" },
    { country: "Barbados", code: "BBD", symbol: "Bds$" },
    { country: "Trinidad and Tobago", code: "TTD", symbol: "TT$" },
    { country: "Bahamas", code: "BSD", symbol: "B$" },
    { country: "Dominican Republic", code: "DOP", symbol: "RD$" },
    { country: "Haiti", code: "HTG", symbol: "G" },
    { country: "Singapore", code: "SGD", symbol: "S$" },
    { country: "Malaysia", code: "MYR", symbol: "RM" },
    { country: "Indonesia", code: "IDR", symbol: "Rp" },
    { country: "Philippines", code: "PHP", symbol: "₱" },
    { country: "Thailand", code: "THB", symbol: "฿" },
    { country: "South Korea", code: "KRW", symbol: "₩" },
    { country: "Turkey", code: "TRY", symbol: "₺" },
    { country: "Saudi Arabia", code: "SAR", symbol: "﷼" },
    { country: "United Arab Emirates", code: "AED", symbol: "د.إ" },
    { country: "Qatar", code: "QAR", symbol: "﷼" },
    { country: "Israel", code: "ILS", symbol: "₪" },
    { country: "Egypt", code: "EGP", symbol: "E£" },
    { country: "Argentina", code: "ARS", symbol: "$" },
    { country: "Chile", code: "CLP", symbol: "$" },
    { country: "Colombia", code: "COP", symbol: "$" },
    { country: "Venezuela", code: "VES", symbol: "Bs.S" },
    { country: "Vietnam", code: "VND", symbol: "₫" },
    { country: "Pakistan", code: "PKR", symbol: "₨" },
    { country: "Bangladesh", code: "BDT", symbol: "৳" },
    { country: "Sri Lanka", code: "LKR", symbol: "Rs" }
]